
class MM_NightmareSpectre : MM_Pinky
{
	Default
	{
		Health 300;
		PainChance 100;
		Speed 15;
		Radius 30;
		Height 56;
		Mass 400;
		Monster;
		Scale 1.2;
		+FLOORCLIP
		+NOFEAR
		SeeSound "Nightmarepinky/see";
		AttackSound "Nightmarepinky/Attack";
		DeathSound "Nightmarepinky/death";
		PainSound "Nightmarepinky/Pain";		
		ActiveSound "Nightmarepinky/Active";
		RenderStyle "subtract";
		BloodColor "Blue";
		Obituary "%o was eaten by a Nightmare Spectre.";
		Tag "Nightmare spectre";
	}
	States
	{
	Spawn:
		NSMS AABB 10 A_Look;
		Loop;
	See:
		NSMS AABBCCDD 2 Fast A_Chase;
		Loop;
	Melee:
		NSMS E 6 Fast A_FaceTarget;
		NSMS F 7 Fast A_FaceTarget;
		NSMS G 8 Fast A_SargAttack;
		Goto See;
	Pain:
		NSMS H 2;
		NSMS H 2 A_Pain;
		Goto See;
	Death.Ice:
		NSMS H 5 A_GenericFreezeDeath;
		TNT1 A 1 A_Freezedeathchunks;
		wait;
	Death:
		NSMS I 8;
		NSMS J 8 A_Scream;
		NSMS K 4;
		NSMS L 4 A_NoBlocking;
		NSMS M 4;
		NSMS N -1;
		Stop;
	XDeath:
		NSSG A 4;
		NSSG B 4 A_XScream;
		NSSG C 4 A_NoBlocking();
		NSSG DEFGHI 4;
		NSSG J -1;
		Stop;
	Raise:
		NSMS MLKJ 5;
		NSMS I 5;
		Goto See;
	}
}

Class MM_DeadNightmarespectre : MM_NightmareSpectre
{
	Default
	{
		-COUNTKILL
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Die("spawndeath");
			Stop;
		Idle:
			NSMS AB 10 A_Look;
			Loop;
		Death.Spawndeath:
			NSMS N 0 A_NoBlocking;
			NSMS N 0 A_Jump(80, "Gibbed");
			NSMS N -1;
			Stop;
		Gibbed:
			NSSG J -1;
			Stop;
	}
}

class MM_NightmareSpectrealt : MM_NightmareSpectre
{
	States
	{
	Spawn:
		SARG AABB 10 A_Look;
		Loop;
	See:
		SARG AABBCCDD 2 Fast A_Chase;
		Loop;
	Melee:
		SARG E 6 Fast A_FaceTarget;
		SARG F 7 Fast A_FaceTarget;
		SARG G 8 Fast A_SargAttack;
		Goto See;
	Pain:
		SARG H 2;
		SARG H 2 A_Pain;
		Goto See;
	Death.Ice:
		SARG H 5 A_GenericFreezeDeath;
		TNT1 A 1 A_Freezedeathchunks;
		wait;
	Death:
		SARG I 8;
		SARG J 8 A_Scream;
		SARG K 4;
		SARG L 4 A_NoBlocking;
		SARG M 4;
		SARG N -1;
		Stop;
	XDeath:
		SARX A 4;
		SARX B 4 A_XScream;
		SARX C 4 A_NoBlocking();
		SARX DEFGHI 4;
		SARX J -1;
		Stop;
	Raise:
		SARG NMLKJ 5;
		SARG I 5;
		Goto See;
	}
}

class MM_SuperNightmareSpectre : MM_Nightmaredemon
{
	Default
	{
		RenderStyle "subtract";
		Health 500;
		BloodColor "Cyan";
	}
	States
	{
	Spawn:
		SNMD AABB 10 A_Look;
		Loop;
	See:
		SNMD AABBCCDD 2 A_Chase;
		Loop;
	Melee:
		SNMD EF 8 A_FaceTarget;
		SNMD G 8 A_SargAttack;
		Goto See;
	Pain:
		SNMD H 2;
		SNMD H 2 A_Pain;
		Goto See;
	Death.Ice:
		SNMD H 5 A_GenericFreezeDeath;
		TNT1 A 1 A_Freezedeathchunks;
		wait;
	Death:
		SNMD I 8;
		SNMD J 8 A_Scream;
		SNMD K 4;
		SNMD L 4 A_NoBlocking;
		SNMD M 4;
		SNMD N -1;
		Stop;
	Raise:
		SNMD M 5;
		SNMD LKJI 5;
		Goto See;
	XDeath:
		SNMD O 4;
		SNMD P 4 A_XScream;
		SNMD Q 4 A_NoBlocking();
		SNMD RSTUVW 4;
		SNMD X -1;
		Stop;
	Death.SSGGIBING:
		TNT1 A 0 A_Jumpifcloser(128, "XDeath");
		TNT1 A 0 A_Jump(256, "Death");
		Goto Death;
	Crush:
		POL5 A 0;
		POL5 A 0 A_Startsound("Bloody/crush");
		POL5 A -1;
		stop;
	}
}
