
Class MM_Spectrespawner : MM_Monsterspawners
{
	Default
	{
		+SHADOW
		RenderStyle "OptFuzzy";
		Radius 30;
		Height 64;
		Alpha 0.25;
	}
	
		void A_Spectrespawn()
	{
		A_NoBlocking();
		if (CallACS("Spectreskintoggle")==1)
		{
			A_SpawnItemEx("MM_Classic_Spectre",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
		}
		else
		{
			A_SpawnItemEx("MM_Spectre",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
		}
	}
	
	States
	{
	Spawn:
		SPC2 G 0;
		Goto spawncheck;
	KDIKDIZDSpawn:
	Goingdownspawn:
	DoomZerospawn:
	D64D2spawner:
	Eviternityspawn:
	Scythe2spawn:
	AAilenspawn:
	TNTRevoSpawn:
	JenesisSpawner:
	Epic2spawner:
	Alternatespawn:
	Normalspawn:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Spectrespawn();
		Stop;
	Ultimatedoomspawn:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_JumpIf(CallACS("UdoomSpectrescript")==4, "Nightmarespawn");
		TNT1 A 0 A_JumpIf(CallACS("UdoomSpectrescript")==3, "Skeletonspawn");
		TNT1 A 0 A_JumpIf(CallACS("UdoomSpectrescript")==2, "Normalspawn");
		TNT1 A 0 A_Jump(50, "Nightmarespawn");
		TNT1 A 0 A_CheckBlock("Normalspawn");
		TNT1 A 0 A_Jump(30, "Skeletonspawn");
		Goto normalspawn;
	Nightmarespawn:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_JumpIf(CallACS("Bonusspawntoggle")==1, "NDspawnContinued");
		goto Normalspawn;
	NDspawnContinued:
		TNT1 A 0 A_SpawnItemEx("MM_NightmareSpectre",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
		Stop;
	Skeletonspawn:
		TNT1 A 0 A_JumpIf(CallACS("UdoomSpectrescript")==6, "Normalspawn");
		TNT1 A 0 A_SpawnItemEx("MM_D1_Revenant",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
		Stop;
	Valiantspawn:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItemEx("MM_CyberSpectre",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
		Stop;
	}
}

class MM_Spectre : MM_Pinky
{
	Default
	{
		+SHADOW
		//RenderStyle "Translucent";
		RenderStyle "OptFuzzy";
		Alpha 0.25;
		SeeSound "demon/sight";
		AttackSound "demon/melee";
		PainSound "demon/pain";
		DeathSound "demon/death";
		ActiveSound "demon/active";
		Obituary "\cg%o was eaten by a Spectre";
		Tag "Spectre Demon";
	}
	States
	{
	Spawn:
		SPTR AB 10 A_Look;
		Loop;
	See:
		SPTR AABBCCDD 2 Fast A_Chase;
		Loop;
	Melee:
		SPTR EF 8 Fast A_FaceTarget;
		SPTR G 8 Fast A_SargAttack;
		Goto See;
	Pain:
		SPTR H 2 Fast A_FadeTo (0.25, 0.1667, false);
		SPTR H 2 Fast A_Pain;
		Goto See;
	Death.Ice:
		SPTR H 5 A_GenericFreezeDeath;
		TNT1 A 1 A_Freezedeathchunks;
		wait;
	Death:
		SPTR I 8 A_FadeTo (1, 0.1667, false);
		SPTR J 0 A_FadeTo (1, 0.1667, false);
		SPTR J 8 A_Scream;
		SPTR K 4 A_FadeTo (1, 0.1667, false);
		SPTR K 0 A_FadeTo (1, 0.1667, false);
		SPTR L 4 A_NoBlocking;
		SPTR M 4 A_FadeTo (1, 0.1667, false);
		SPTR N -1;
		Stop;
	Raise:
		SPTR M 5 A_FadeTo (0.25, 0.1667, false);
		SPTR LKJI 5 A_FadeTo (0.25, 0.1667, false);
		Goto See;
	XDeath:
		SPRX A 4 A_FadeTo (1, 0.1667, false);
		SPRX B 4 A_XScream;
		SPRX B 0 A_FadeTo (1, 0.1667, false);
		SPRX C 4 A_NoBlocking();
		SPRX C 0 A_FadeTo (1, 0.1667, false);
		SPRX DEFGHI 4 A_FadeTo (1, 0.1667, false);
		SPRX J -1;
		Stop;
	}
}

class MM_Classic_Spectre : MM_Spectre
{
	default
	{
		RenderStyle "OptFuzzy";
	}
	States
	{
	Spawn:
		SPC2 AB 10 A_Look;
		Loop;
	See:
		SPC2 AABBCCDD 2 Fast A_Chase;
		Loop;
	Melee:
		SPC2 EF 8 Fast A_FaceTarget;
		SPC2 G 8 Fast A_SargAttack;
		Goto See;
	Pain:
		SPC2 H 2 Fast;
		SPC2 H 2 Fast A_Pain;
		Goto See;
	Death.Ice:
		SPC2 H 5 A_GenericFreezeDeath;
		TNT1 A 1 A_Freezedeathchunks;
		wait;
	Death:
		SPC2 I 8 A_FadeTo (1, 0.1667, false);
		SPC2 J 0 A_FadeTo (1, 0.1667, false);
		SPC2 J 8 A_Scream;
		SPC2 K 4 A_FadeTo (1, 0.1667, false);
		SPC2 K 0 A_FadeTo (1, 0.1667, false);
		SPC2 L 4 A_NoBlocking;
		SPC2 M 4 A_FadeTo (1, 0.1667, false);
		SPC2 N -1;
		Stop;
	Raise:
		SPC2 N 5 A_FadeTo (0.25, 0.1667, false);
		SPC2 MLKJI 5 A_FadeTo (0.25, 0.1667, false);
		Goto See;
	XDeath:
		SC2X A 4 A_FadeTo (1, 0.1667, false);
		SC2X B 4 A_XScream;
		SC2X B 0 A_FadeTo (1, 0.1667, false);
		SC2X C 4 A_NoBlocking();
		SC2X C 0 A_FadeTo (1, 0.1667, false);
		SC2X DEFGHI 4 A_FadeTo (1, 0.1667, false);
		SC2X J -1;
		Stop;
	}
}

Class MM_DeadSpectre : MM_Spectre
{
	Default
	{
		-COUNTKILL
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Die("spawndeath");
			Stop;
		Idle:
			SPTR A 0 A_JumpIf(CallACS("Spectreskintoggle")==1, "OriginalIdle");
			SPTR AB 10 A_Look;
			SPTR B 0 A_JumpIf(CallACS("Spectreskintoggle")==1, "OriginalIdle");
			Loop;
		OriginalIdle:
			SPC2 A 0 A_JumpIf(CallACS("Spectreskintoggle")==0, "Idle");
			SPC2 AB 10 A_Look;
			SPC2 A 0 A_JumpIf(CallACS("Spectreskintoggle")==0, "Idle");
			Loop;
		Death.Spawndeath:
			SPTR N 0 { A_NoBlocking(); A_FadeTo (1, 1, false); }
			SPTR N 0 A_Jump(100, "Gibbed");
			SPTR N 0 A_JumpIf(CallACS("Spectreskintoggle")==1, "OriginalSpawndeath");
			SPTR N -1;
			Stop;
		OriginalSpawndeath:
			SPC2 N -1;
			Loop;
		Gibbed:
			SPTR N 0 A_JumpIf(CallACS("Spectreskintoggle")==1, "OriginalGibbed");
			SPRX J -1;
			Stop;
		OriginalGibbed:
			SC2X J -1;
			Stop;
	}
}

class MM_CyberSpectre : MM_CyberPinky
{
	Default
	{
		+SHADOW
		RenderStyle "OptFuzzy";
		Alpha 0.25;
		Obituary "$OB_SPECTREHIT";
		Tag "Cyber Spectre";
	}
	
		Void A_Pinkywalk()
	{
		A_Chase();
		A_StartSound("Mecha/walk", CHAN_BODY, CHANF_DEFAULT, 1, ATTN_IDLE);
	}
	
	States
	{
	Spawn:
		MESC AB 10 A_Look;
		Loop;
	See:
		MESC A 2 A_Pinkywalk();
		MESC ABB 2 A_Chase;
		MESC C 2 A_Pinkywalk();
		MESC CDD 2 A_Chase;
		Loop;
	Melee:
		MESC EF 3 Fast A_FaceTarget;
		MESC G 18 Fast A_SargAttack;
		Goto See;
	Pain:
		MESC H 2 Fast;
		MESC H 2 Fast A_Pain;
		Goto See;
	Death.Ice:
		MESC H 5 A_GenericFreezeDeath;
		TNT1 A 1 A_Freezedeathchunks;
		wait;
	Death:
		MESC I 1 A_SetRenderStyle(0.25, STYLE_Translucent);
		MESC I 7 A_FadeTo (1, 0.1667, false);
		MESC J 0 A_FadeTo (1, 0.1667, false);
		MESC J 8 A_Scream;
		MESC K 4 A_FadeTo (1, 0.1667, false);
		MESC K 0 A_FadeTo (1, 0.1667, false);
		MESC L 4 A_NoBlocking;
		MESC M 4 A_FadeTo (1, 0.1667, false);
		MESC N -1;
		Stop;
	Raise:
		MESC N 5 A_FadeTo (0.25, 0.1667, false);
		MESC MLKJI 5 A_FadeTo (0.25, 0.1667, false);
		Goto See;
	XDeath:
		MESC O 4 A_FadeTo (1, 0.1667, false);
		MESC P 4 A_XScream;
		MESC P 0 A_FadeTo (1, 0.1667, false);
		MESC Q 4 A_NoBlocking();
		MESC Q 0 A_FadeTo (1, 0.1667, false);
		MESC RSTUVW 4 A_FadeTo (1, 0.1667, false);
		MESC X -1;
		Stop;
	}
}