
class MM_PlasmaGunMKII : Slaughterweapon
{
	Default
	{
		Weapon.SelectionOrder 100;
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 50;
		Weapon.AmmoType "Cell";
		Weapon.UpSound "Weapons/Plasmaup";
		Inventory.PickupSound "Weaopns/PlasmaPickup";
		Inventory.PickupMessage "\cgYou got the mkII Plasmagun! What an upgrade!";
		Tag "$TAG_PLASMARIFLE";
	}
	
		Action Void A_FirePlasmaMKII()
		{
			//A_GunFlash("Flash"); 
			A_FireProjectile("MM_Greenplasma2",0,1,-1);
		}
		
	States
	{
	Ready:
		PLM2 A 0 A_Startsound("RailGun/Idle", CHAN_WEAPON, CHANF_LOOPING, 1, ATTN_NORM);
		PLM2 AB 2 A_WeaponReady;
		Loop;
	Deselect:
		PLM2 A 0 A_Stopsound(CHAN_WEAPON);
		PLM2 A 0 A_Lower;
		PLM2 A 1 A_Lower;
		Loop;
	Select:
		PLM2 A 0 A_Stopsound(CHAN_WEAPON);
		PLM2 A 0 A_Raise;
		PLM2 A 1 A_Raise;
		Loop;
	Fire:
		RAIL A 0 A_Stopsound(CHAN_WEAPON);
		PM2F A 1 Bright A_FirePlasmaMKII();
		PM2F B 1 Bright;
		PLM2 C 1 Bright;
		TNT1 A 0 A_ReFire;
		Goto Ready;
	Flash:
		Goto LightDone;
	Spawn:
		PMM2 F -1 Bright;
		Stop;
	}
}

class MM_Greenplasma2 : MM_Greenplasma
{
	Default
	{
		Speed 40;
	}
}

Class MM_PlasmagunmkIIpickup : CustomInventory 
{
Default
{
	INVENTORY.RESTRICTEDTO "ET_Player_Slaughter";
	VISIBLETOPLAYERCLASS "ET_Player_Slaughter";
	//Inventory.PickupSound "Weapons/PistolPickup";
	Inventory.PickupMessage "\cgYou got the mkII Plasmagun! What an upgrade!";
}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIfInventory("MM_PlasmaGunMKII", 1, "Taken");
		PMM2 A -1;
		Stop;
	Pickup:
		TNT1 A 0 A_GiveInventory("MM_PlasmaGunMKII", 1);
		Stop;
	Taken:
		TNT1 A 0;
		Fail;	
	}
}