
class MM_Mechabus : MM_mancubus 
{
	Default
	{
	Gibhealth 40;
	+NOINFIGHTSPECIES
	+DONTHARMSPECIES
	+DONTMORPH
	+DONTHARMCLASS
	+noradiusdmg
	+MissileMore
	+SEEINVISIBLE
	Scale 1.1;
	PainChance 0;
	PainChance "BERSERKEDFIST", 256;
	DamageFactor "BERSERKEDFIST", 0.5;
	SeeSound "Mechabus/Sight";
	PainSound "Mechabus/pain";
	DeathSound "Mechabus/Death";
	ActiveSound "Mechabus/Active";
	Tag "Cyber mancubus";
	}
	
	bool dearmored; 
	
	void A_ManAttack1()
	{
		A_FaceTarget();
		A_SpawnProjectile("MM_ToxicShot",22,34,20);
		A_SpawnProjectile("MM_ToxicShot",22,-34,0);
	}
	
	void A_ManAttack2()
	{
		A_FaceTarget();
		A_SpawnProjectile("MM_ToxicShot",22,34,0);
		A_SpawnProjectile("MM_ToxicShot",22,-34,-20);
	}
	
	void A_ManAttack3()
	{
		A_FaceTarget();
		A_SpawnProjectile("MM_ToxicShot",22,34,8);
		A_SpawnProjectile("MM_ToxicShot",22,-34,-8);
	}
	
	void A_ManAttack4()
	{
		A_FaceTarget();
		A_SpawnProjectile("FireTrail",22,34,8);
		A_SpawnProjectile("FireTrail",22,-34,-8);
	}
	
	States
	{
	Spawn:
		CFAT A 0;
		CFAT A 0 {DeArmored = False;}
		Goto Idle;
	Idle:
		"####" AB 15 A_Look;
		Loop;
	See:
		"####" AABBC 4 A_Chase;
		"####" C 4 A_Manwalk();
		"####" DDEEF 4 A_Chase;
		"####" F 4 A_Manwalk();
		Loop;
	Missile:
		"####" G 0 A_Startsound("Mechabus/Attack");
		"####" G 20 A_Facetarget();
		"####" H 10 BRIGHT A_ManAttack1();
		"####" IG 5 A_FaceTarget;
		"####" H 10 BRIGHT A_ManAttack2();
		"####" IG 5 A_FaceTarget;
		"####" H 10 BRIGHT A_ManAttack3();
		"####" IG 5 A_FaceTarget;
		Goto See;
	Pain:
		"####" J 3;
		"####" J 3 A_Pain;
		Goto See;
	Pain.BERSERKEDFIST:
		CFNA J 0 Bright {}
		CFNA J 0 Bright 
		{
			DeArmored = true;
			bnoradiusdmg = false;
			Painchance = 80;
			bMissileevenMore = true;
			bSEEINVISIBLE = false;
			//PainChance "BERSERKEDFIST" = 80;
		}
		CFNA J 3;
		CFNA J 6 A_Pain;
		Goto See;
	Death:
		CFAT K 0 A_Jumpif(DeArmored == true, "DeathDearmored");
		CFAT K 6 Bright;
		CFAT L 6 Bright A_Scream;
		CFAT M 6 Bright A_NoBlocking;
		CFAT NOPQ 6 Bright;
		CFAT RS 6;
		CFAT T -1 A_BossDeath;
		Stop;
	DeathDearmored:
		CFNA K 6;
		CFNA L 6 A_Scream;
		CFNA M 6 A_NoBlocking;
		CFNA NOPQRS 6;
		CFNA T -1 A_BossDeath;
		Stop;
	Raise:
		Stop;
	XDeath:
		Stop;
	Crush:
		BAGI A 0;
		BAGI A 0 A_Startsound("Bloody/crush");
		BAGI A -1;
		stop;
	}
}

class MM_ToxicShot : MancubusShot
{
	Default
	{
		DamageType "Enemydamage";
		Renderstyle "Add";
		+ZDOOMTRANS
		Speed 30;
	}
	
	Void A_ManPPtrail()
	{
			A_SpawnItemEx("MM_Toxictrail", 0, 0, -2, 0, 0, 0, 0, 128);
	}

	States
	{
	Spawn:
		HECF A 0 nodelay A_JumpIf(CallACS("Projtoggle")==1, "AltSpawn");
		HECF AB 3 Bright;
		HECF A 0 A_JumpIf(CallACS("Projtoggle")==1, "AltSpawn");
		Loop;
	AltSpawn:
		HEC2 AAABBB 1 BRIGHT A_ManPPtrail();
		Goto spawn;
	Death:
		HECF C 8 BRIGHT A_Explode(20,20);
		HECF D 6 BRIGHT;
		HECF E 4 BRIGHT;
		Stop;
	}
}

Class MM_Toxictrail : Fatsotrail
{
	States
  {
  Spawn:
	TNT1 A 2;
    HEC2 A 1 Bright A_SetScale(0.90);
	HEC2 B 1 Bright A_SetScale(0.80);
	HEC2 A 1 Bright A_SetScale(0.70);
	HEC2 B 1 Bright A_SetScale(0.60);
	HEC2 A 1 Bright A_SetScale(0.50);
	HEC2 B 1 Bright A_SetScale(0.40);
	HEC2 A 1 Bright A_SetScale(0.30);
	HEC2 B 1 Bright A_SetScale(0.20);
	HEC2 A 1 Bright A_SetScale(0.10);
    Stop;
  }
}

class MM_ToxicBall : Baronball
{
	Default
	{
		Radius 6;
		Height 16;
		Speed 25;
		Damage 2;
		Projectile ;
		+RANDOMIZE
		+ZDOOMTRANS
		-NOGRAVITY
		-FLOAT
		RenderStyle "Add";
		Alpha 1;
		SeeSound "baron/attack";
		painsound "TOXICBALL/Pain";
		DeathSound "TOXICBALL/Death";
	}
	States
	{
	Spawn:
		TOXC AB 4 BRIGHT;
		Loop;
	Death:
		TOXC CD 7 BRIGHT;
		TOXC FGH 8 BRIGHT;
		TOXC I 7 BRIGHT A_pain;
		TOXC J 4 BRIGHT;
		TOXC L 2 BRIGHT;
		TOXC M 6 BRIGHT A_Explode;
		TOXC D 6 BRIGHT;
		TOXC E 6;
		Stop;
	}
}

class MM_EXPlasmaTrail1 : MM_PlasmaTrail1
{
	States
	{
	Spawn:
		EXPL AA 2 Bright A_fadeout(0.3);
		Loop;
	}
}

class MM_EXPlasmaTrail2 : MM_EXPlasmaTrail1
{
	States
	{
	Spawn:
		EXPL BB 2 Bright A_fadeout(0.3);
		Loop;
	}
}

class MM_EXPlasmaTrail3 : MM_EXPlasmaTrail1
{
	States
	{
	Spawn:
		EXPL CC 2 Bright A_fadeout(0.3);
		Loop;
	}
}

class MM_EXPlasmaTrail4 : MM_EXPlasmaTrail1
{
	States
	{
	Spawn:
		EXPL DD 2 Bright A_fadeout(0.3);
		Loop;
	}
}

class ExplosivePlasma : Actor
{
	Default
	{
		Radius 13;
		Height 8;
		Speed 30;
		Damage 20;
		Projectile;
		+RANDOMIZE
		+DEHEXPLOSION
		+ZDOOMTRANS
		Alpha 0.75;
		RenderStyle "Add";
		DamageType "Enemydamage";
		SeeSound "Exploplas/sight";
		DeathSound "Exploplas/death";
		Obituary "$OB_MPROCKET";
	}
	States
	{
	Spawn:
		EXPL AAA 1 Bright A_SpawnItemEx("MM_EXPlasmaTrail1", -12, 0, 0, 0, 0, 0, 0, 128);
		EXPL BBB 1 Bright A_SpawnItemEx("MM_EXPlasmaTrail2", -12, 0, 0, 0, 0, 0, 0, 128);
		EXPL CCC 1 Bright A_SpawnItemEx("MM_EXPlasmaTrail3", -12, 0, 0, 0, 0, 0, 0, 128);
		EXPL DDD 1 Bright A_SpawnItemEx("MM_EXPlasmaTrail4", -12, 0, 0, 0, 0, 0, 0, 128);
		Loop;
	Death:
		BFE2 E 8 Bright A_Explode;
		BFE2 A 6 Bright;
		BFE2 B 4 Bright;
		BFE2 C 2 Bright;
		Stop;
	}
}