
class MM_Vassago : Actor
{
	Default
	{
		Health 1200;
		Radius 24;
		Height 64;
		Mass 1000;
		Speed 8;
		PainChance 100;
		ReactionTime 8;
		Monster;
		+FLOORCLIP
		+BOSSDEATH
		+DONTHARMCLASS
		+NOINFIGHTSPECIES
		+NOICEDEATH
		Species "BaronOfHell";
		Scale 1.2;
		SeeSound "Vassago/sight";
		PainSound "Vassago/pain";
		DeathSound "Vassago/death";
		ActiveSound "Vassago/active";
		Obituary "";
		HitObituary "";
		Tag "Vassago";
	}
	
	Void A_Noblewalk()
	{
		A_Chase();
		A_StartSound("Heavynoble/Walk", CHAN_BODY, CHANF_DEFAULT, 1, ATTN_IDLE);
	}
	
	Void A_Pyrosoul()
	{
		if (CallACS("Projtoggle")==1)
		{
			A_SpawnProjectile("MM_PyroSoul",86,0,0,2,-90);
		}
	}
	
	Void A_VassCry()
	{
		A_Startsound("Vassago/attack", CHAN_VOICE);
		A_FaceTarget();
	}
	
	Void A_Vassattack()
	
	{
		A_CustomComboAttack("MM_VassagoFlame", 40, 40, "baron/melee");
		A_Facetarget();
	}
	
		Void A_TripleVassagoAttack()
	
	{
		A_FaceTarget();
		A_CustomComboAttack("MM_Vassagofire2", 30, 40, "baron/melee");
		A_SpawnProjectile("MM_Vassagofire2",30,0,-15,0);
		A_SpawnProjectile("MM_Vassagofire2",30,0,15,0);
		A_SpawnProjectile("MM_Vassagofire2",30,0,-30,0);
		A_SpawnProjectile("MM_Vassagofire2",30,0,30,0);
	}
	
	States
	{
	Spawn:
		VASS AB 10 A_Look ;
		Loop;
	See:
		VASS A 3 A_Noblewalk();
		VASS ABB 3 A_Chase;
		VASS C 3 A_Noblewalk();
		VASS CDD 3 A_Chase;
		Loop;
	Melee:
	Missile:
		VASS E 0 A_Jump(100, "Missile2");
		VASS E 0 A_VassCry();
		VASS E 8 A_FaceTarget;
		VASS FG 4 A_FaceTarget;
		VASS H 8 A_Vassattack();
		Goto See;
	Missile2:
		VASS E 6 A_FaceTarget;
		VASS FG 4 A_FaceTarget;
		VASS H 8 A_TripleVassagoAttack();
		Goto See;
	Pain:
		VASS I  2;
		VASS I  2 A_Pain;
		Goto See;
	Death:
		VASS J 8 Bright;
		VASS K 8 Bright A_Scream;
		VASS L 7 Bright;
		VASS M 6 Bright { A_NoBlocking(); A_Pyrosoul(); }
		VASS NO 6 Bright;
		VASS P 7 Bright;
		VASS Q -1 A_BossDeath;
		stop;
	Death.SSGGIBING:
		Goto Death;
	raise:
		VASS P 8 bright;
		VASS ONMLKJ 8 bright;
		goto see;
	}
}

class MM_VassagoFlame : Actor
{
	Default
	{
		Radius 6;
		Height 16;
		Speed 15;
		FastSpeed 20;
		Damage 5;
		Projectile ;
		+RANDOMIZE
		+ZDOOMTRANS
		RenderStyle "Add";
		Alpha 1;
		SeeSound "Vassago/Shot";
		DeathSound "Vassago/ShotX";
		//Decal "BaronScorch";
	}
	
		Void A_Trail2()
	{
		if (CallACS("Projtoggle")==1)
		{
			A_SpawnItemEx("MM_Vassagoflametrail", 0, 0, 0, 0, 0, 0, 0, 128);
			A_SpawnItemEx("Ball1Trail", 0, 0, 0, 0, 0, 0, 0, 128);
		}
		else
		{
			
		}
	}
	
		Void A_Trail1()
	{
		if (CallACS("Projtoggle")==1)
		{
			A_SpawnItemEx("MM_Vassagoflametrail", 0, 0, 0, 0, 0, 0, 0, 128);
		}
		else
		{
			
		}
	}
	
	States
	{
		Spawn:
			VFLM AAA 1 BRIGHT A_Trail1();
			VFLM A 1 BRIGHT A_Trail2();
			VFLM BBB 1 BRIGHT A_Trail1();
			VFLM B 1 BRIGHT A_Trail2();
			Loop;
		death:
			VFLM C 0 Bright
			{
				bNOGRAVITY = false;
				A_ChangeLinkFlags(0);
			}
			VFLM C 0 Bright A_Startsound("Vassago/fire");
			VFLM C 4 bright A_Explode(10,130);
			VFLM D 4 bright;
			VFLM E 4 bright;
			VFLM F 0 bright A_Startsound("Vassago/fire");
			VFLM F 4 bright A_Explode(10,130);
			VFLM G 4 bright;
			VFLM H 4 bright;
			VFLM F 0 bright A_Startsound("Vassago/fire");
			VFLM F 4 bright A_Explode(10,130);
			VFLM G 4 bright;
			VFLM H 4 bright;
			VFLM F 0 bright A_Startsound("Vassago/fire");
			VFLM F 4 bright A_Explode(10,130);
			VFLM G 4 bright;
			VFLM H 4 bright;
			VFLM F 0 bright A_Startsound("Vassago/fire");
			VFLM F 4 bright A_Explode(10,130);
			VFLM G 4 bright;
			VFLM H 4 bright;
			VFLM F 0 bright A_Startsound("Vassago/fire");
			VFLM F 4 bright A_Explode(10,130);
			VFLM G 4 bright;
			VFLM H 4 bright;
			VFLM F 0 bright A_Startsound("Vassago/fire");
			VFLM F 4 bright A_Explode(10,130);
			VFLM G 4 bright;
			VFLM H 4 bright;
			VFLM F 0 bright A_Startsound("Vassago/fire");
			VFLM F 4 bright A_Explode(10,130);
			VFLM G 4 bright;
			VFLM H 4 bright;
			VFLM I 0 bright A_Startsound("Vassago/fire");
			VFLM I 4 bright A_Explode(10,130);
			VFLM J 4 bright;
			VFLM K 4 bright;
			VFLM L 4 bright A_Explode(10,130);
			VFLM MNOPQ 4 bright;
			stop;
	}
}

class MM_Vassagoflametrail : MM_BaronBalltrail
{
	States
	{
	Spawn:
		tnt1 A 2; 
		VFTL AABBCCDD 1 Bright A_Fadeout;
		Stop;
	}
}

class MM_Vassagofire2 : Fatshot
{
	Default
	{
		Speed 12;
		Scale 1.0;
		Radius 13;
		Height 8;
		Damage 5;
		+RANDOMIZE
		+NODAMAGETHRUST
		+HITTRACER
	}
	States
	{
		Spawn:
			BAL1 AB 4 BRIGHT;
			Loop;
		Death:
			MNFX A 8 BRIGHT A_SpawnItemEx("MM_Fireeffectdamage",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS,0,0);
			MNFX B 6 BRIGHT;
			MNFX C 4 BRIGHT;
			Stop;
	}
}


Class MM_Fireeffectdamage : actor
{
	Default
	{
		+NOBLOCKMAP
		Radius 13;
		Height 8;
		+NOGRAVITY
		+ALLOWPARTICLES
		+RANDOMIZE
		+HITTRACER
		Scale 0.7;
		Renderstyle "Add";
	}
	States
	{
	Spawn:
      VFLA ABA 2 Bright A_DamageTracer(5,"Fire",DMSS_AFFECTARMOR,"None","None",AAPTR_TARGET);
	  VFLA B 2 Bright {A_FireCrackle(); A_DamageTracer(5,"Fire",DMSS_AFFECTARMOR,"None","None",AAPTR_TARGET);}
	  VFLA A 2 Bright {A_Fire(1); A_DamageTracer(5,"Fire",DMSS_AFFECTARMOR,"None","None",AAPTR_TARGET);}
	  VFLA BCB 2 Bright {A_Fire(1); A_DamageTracer(4,"Fire",DMSS_AFFECTARMOR,"None","None",AAPTR_TARGET);}	  
	  VFLA CBCD 2 Bright {A_Fire(1); A_DamageTracer(3,"Fire",DMSS_AFFECTARMOR,"None","None",AAPTR_TARGET);}	  
	  VFLA CDEDEF 2 Bright {A_Fire(1); A_DamageTracer(2,"Fire",DMSS_AFFECTARMOR,"None","None",AAPTR_TARGET);}	  
	  VFLA EFEFGHGHGH 2 Bright A_Fire(1);
      stop;
	}
}